# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Two' do
  use_frameworks!

  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'JSQMessagesViewController'
  pod 'GoogleSignIn'
end
